---
version: "3.6"
services:

  transmission-sonarr:
      image: linuxserver/transmission:latest
      container_name: "transmission-sonarr"
      restart: unless-stopped
      networks:
        - my-network
      ports:
        - 9092:9091
        - 51414:51413
        - 51414:51413/udp
      dns:
        - 1.1.1.1
        - 8.8.8.8
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ${CONFIG_PATH}/transmission-sonarr:/config
        - ${DATA_PATH}:/data
      environment:
        - PGID=${PGID}
        - PUID=${PUID}
        - TRANSMISSION_RATIO_LIMIT_ENABLED=true
        - TRANSMISSION_DOWNLOAD_DIR=/data/Séries
        - GLOBAL_APPLY_PERMISSIONS=false
        - TRANSMISSION_HOME=/config/transmission-home
        - TZ=Europe/Paris

  transmission-radarr:
      image: linuxserver/transmission:latest
      container_name: "transmission-radarr"
      restart: unless-stopped
      networks:
        - my-network
      ports:
        - 9091:9091
        - 51413:51413
        - 51413:51413/udp
      dns:
        - 1.1.1.1
        - 8.8.8.8
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ${CONFIG_PATH}/transmission-radarr:/config
        - ${DATA_PATH}:/data
      environment:
        - PGID=${PGID}
        - PUID=${PUID}
        - TRANSMISSION_RATIO_LIMIT_ENABLED=true
        - TRANSMISSION_DOWNLOAD_DIR=/data/Films
        - GLOBAL_APPLY_PERMISSIONS=false
        - TRANSMISSION_HOME=/config/transmission-home
        - TZ=Europe/Paris

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}0
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    networks:
      - my-network
    dns:
        - 1.1.1.1
        - 8.8.8.8
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:develop-alpine
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=022
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${DATA_PATH}/Séries/:/tv
      - ${DATA_PATH}/downloads:/downloads
    networks:
      - my-network
    dns:
        - 1.1.1.1
        - 8.8.8.8
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:nightly-alpine
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=022
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${DATA_PATH}/Films/:/movies
      - ${DATA_PATH}/downloads:/downloads
    networks:
      - my-network
    dns:
        - 1.1.1.1
        - 8.8.8.8
    ports:
      - 7878:7878
    restart: unless-stopped

networks:
  my-network: