---
version: "3.6"
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - ./config/Homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    network_mode: host
  
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    privileged: true
    container_name: zigbee2mqtt
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./config/Zigbee2mqtt:/app/data
    restart: unless-stopped
    devices:
      - ./dev/ttyUSB0:/dev/ttyACM0
    network_mode: host

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./config/Mosquitto:/mosquitto/config
    restart: unless-stopped
    network_mode: host
